# Metrics

## Confusion Matrix

| _ | Predicted: Spam Email | Predicted: Real Email|
| --- | --- | ---|
| Actual: Spam Email | True Positive | False Negative |
| Actual: Real Email | False Positive | True Negative |

The class of interest is the **possitive class**, in this case the class is **Spam**

## Accuracy

$\frac{tp + tn}{tp+tn+fp+fn}$

## Precision

$\frac{tp}{tp+fp}$

## Recall

$\frac{tp}{tp+fn}$

## F1-Score

$2*\frac{precision * recall}{precision + recall}$

## Notes

* **High Precision**: Not many real emails predicted as spam
* **High Recall**: Predicted most spam emails correctly

In [10]:
from sklearn.model_selection import  train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
X = pd.DataFrame(iris.data, columns= iris.feature_names)
y = iris.target.reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.4,
                                                    random_state=42)
knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

[[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.95      1.00      0.97        19
           2       1.00      0.94      0.97        18

    accuracy                           0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60



/usr/lib64/python3.6/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


## Confusion Matrix

In [11]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]


## Classification Report

In [12]:
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.95      1.00      0.97        19
           2       1.00      0.94      0.97        18

    accuracy                           0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60

